### ISSUE TITLE
看了视频，建议使用 -v 的那种模式。。 

### ISSUE THREAD

**Issue by rexleimo** [fecshop/yii2_fecshop_docker#10]
其实 docker run link -v path:containerPath 这种模式，视频中的docker-compose exect php bash 进入容器安装fecshop，如果需要修改代码要这么办？

**Comment by fancyecommerce** [comment]
你说的是，修改fecshop的代码吗？

可以再宿主主机中修改，php的代码是以挂载的方式，挂载到php容器的。
