### ISSUE TITLE
修改php的配置

### ISSUE THREAD

**Issue by xinhongru** [fecshop/yii2_fecshop_docker#13]
libpng12-dev \  这个安装报错 提示已经被废弃  

采用以下的包可以安装：

libpng-dev \ 
# 请更新

**Comment by fancyecommerce** [comment]
Ubuntu 14以上就已经不再支持`libpng12`

docker-composer 安装php报错，`docker Package 'libpng12-dev' has no installation candidate`

解决：将文件：https://github.com/fecshop/yii2_fecshop_docker/blob/master/services/php/docker/Dockerfile#L10

解决方案   `libpng12-dev \`  ------> `libpng-dev \`
