### ISSUE TITLE
Fatal error: require(): Failed opening required '/www/web/fecshop/vendor/autoload.php' 

### ISSUE THREAD

**Issue by yjdwbj** [fecshop/yii2_fecshop_docker#17]
版本:1.6.3.0

./yii migrate --interactive=0 --migrationPath=@fecshop/migrations/mysqldb

Warning: require(/www/web/fecshop/vendor/autoload.php): failed to open stream: No such file or directory in /www/web/fecshop/yii on line 14

Fatal error: require(): Failed opening required '/www/web/fecshop/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /www/web/fecshop/yii on line 14

**Comment by fancyecommerce** [comment]
应该是composer安装出问题了，请参看帖子：http://www.fecshop.com/topic/855

有问题再这个帖子下面讨论
