### ISSUE TITLE
Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

### ISSUE THREAD

**Issue by stevekd** [fecshop/yii2_fecshop_docker#18]
ERROR: for yii2_fecshop_docker_web_1  Cannot start service web: b'driver failed programming external connectivity on endpoint yii2_fecshop_docker_web_1 (68f9be019a79a28e4bbe3bdee73648182955779b53e9ba2eccc18477083091cc): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'

ERROR: for web  Cannot start service web: b'driver failed programming external connectivity on endpoint yii2_fecshop_docker_web_1 (68f9be019a79a28e4bbe3bdee73648182955779b53e9ba2eccc18477083091cc): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'
ERROR: Encountered errors while bringing up the project.

**Comment by stevekd** [comment]
docker-compose up 失败，端口被占用

**Comment by fancyecommerce** [comment]
将宿主主机占用80端口的程序（nginx或者apache）管掉

或者用代理的方式： http://www.fecshop.com/topic/1084
