### ISSUE TITLE
Do not run Composer as root/super user!

### ISSUE THREAD

**Issue by lincome** [fecshop/yii2_fecshop_docker#2]
[
![qq 20180125104251](https://user-images.githubusercontent.com/7379732/35368083-9a9ba8f6-01bc-11e8-91d6-bb6d491dc506.png)
](url)
How to solve the problem

**Comment by fancyecommerce** [comment]
不影响的，继续安装即可。

**Comment by lincome** [comment]
Dockerfile加入ENV COMPOSER_ALLOW_SUPERUSER=1即可
[
![qq 20180127095800](https://user-images.githubusercontent.com/7379732/35467390-9d0061f8-0348-11e8-92ee-3ed04e8a9e01.png)
](url)
