### ISSUE TITLE
php:7.1.13-fpm，此docker镜像的apt源是有问题的

### ISSUE THREAD

**Issue by mxbmxl** [fecshop/yii2_fecshop_docker#21]
报错信息如下
`
$ docker-compose build
mysql uses an image, skipping
mongodb uses an image, skipping
web uses an image, skipping
xunsearch uses an image, skipping
redis uses an image, skipping
Building php
Step 1/11 : FROM php:7.1.13-fpm
7.1.13-fpm: Pulling from library/php
f49cf87b52c1: Pull complete
185616061386: Pull complete
5fc132db2e0d: Pull complete
00c1c323341a: Pull complete
c5fdfbd84ee9: Pull complete
944ca804523d: Pull complete
5f8680da6162: Pull complete
e99c6e5bb99a: Pull complete
2c9454f03781: Pull complete
74b18f859219: Pull complete
Digest: sha256:f92d5587511b3e7b91a9fd34ad2a005dee4a2b95497a66197785eda0d6239466
Status: Downloaded newer image for php:7.1.13-fpm
 ---> 3ac64cb99e11
Step 2/11 : RUN apt-get update && apt-get install -y         libfreetype6-dev         librabbitmq-dev         libssh-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libicu-dev         libxml2-dev         libssl-dev         git         wget         ssh         libpcre3-dev         --no-install-recommends
 ---> Running in f6a45cb162f8
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie-updates InRelease [7340 B]
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [824 kB]
Fetched 10.1 MB in 16s (628 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y         libfreetype6-dev         librabbitmq-dev         libssh-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libicu-dev         libxml2-dev         libssl-dev         git         wget         ssh         libpcre3-dev         --no-install-recommends' returned a non-zero code: 100
`

**Comment by mxbmxl** [comment]
解决办法：
STEP1---编辑 `./services/php/docker/Dockerfile`，
STEP2---在`FROM php:7.1.13-fpm`下面添加如下代码：
```Dockerfile
#更新apt-get源 使用163的源
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib" >>/etc/apt/sources.list
RUN apt-get clean && apt-get update
```

**Comment by vanwhebin** [comment]
![image](https://user-images.githubusercontent.com/8357785/68173028-91fd3f00-ffb4-11e9-992e-6cfba0913714.png)

ubuntu 16.04
aliyun的镜像源

也有问题，下载不下来


使用docker-compose.yml.aliyun文件覆盖之后，直接跳过了
![image](https://user-images.githubusercontent.com/8357785/68178485-2b355100-ffc7-11e9-98d3-047fc1854ee3.png)

**Comment by fancyecommerce** [comment]
有问题，直接官网论坛发帖子：http://www.fecmall.com/topic
