### ISSUE TITLE
关于安装的fecshop的问题

### ISSUE THREAD

**Issue by JummyWu** [fecshop/yii2_fecshop_docker#22]
我在执行
```composer create-project fancyecommerce/fecshop-app-advanced fecshop 1.7.2.0```
遇到了这个问题
```Do not run Composer as root/super user! See https://getcomposer.org/root for details```
请问我需要如何解决呢？？

**Comment by JummyWu** [comment]
然后等了很久都没反应

**Comment by pljay** [comment]
> 然后等了很久都没反应

我也出现相同的问题，你解决了没有

**Comment by kongxiaoan** [comment]
请问你们解决了吗

**Comment by fancyecommerce** [comment]
有问题，直接官网论坛发帖子：http://www.fecmall.com/topic
