### ISSUE TITLE
没有modules这个目录

### ISSUE THREAD

**Issue by haohonglong** [fecshop/yii2_fecshop_docker#23]
根据文档做了如下操作
composer create-project fancyecommerce/fecshop-app-advanced fecshop 2.4.4
。。。
前后台程序运行正常但是分别在appadmin，appfront 文件夹里未发现modules这个文件夹 

![image](https://user-images.githubusercontent.com/12904929/73136016-15926d80-4084-11ea-9dd4-de348e7acf8b.png)

![image](https://user-images.githubusercontent.com/12904929/73135953-635aa600-4083-11ea-8641-7b92c2d98b92.png)

**Comment by haohonglong** [comment]
怎么这么长时间也每个回复！！！

**Comment by fancyecommerce** [comment]
有问题，直接官网论坛发帖子：http://www.fecmall.com/topic
