### ISSUE TITLE
No releases available for package "pecl.php.net/oauth"

### ISSUE THREAD

**Issue by chouyang** [fecshop/yii2_fecshop_docker#24]
> docker-compose build
mysql uses an image, skipping
mongodb uses an image, skipping
web uses an image, skipping
xunsearch uses an image, skipping
redis uses an image, skipping
Building php
Step 1/11 : FROM php:7.1.13-fpm
 ---> 3ac64cb99e11
Step 2/11 : RUN apt-get update && apt-get install -y         libfreetype6-dev         librabbitmq-dev         libssh-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libicu-dev         libxml2-dev         libssl-dev         git         wget         ssh         libpcre3-dev         --no-install-recommends
 ---> Using cache
 ---> 56f4fda98e0b
Step 3/11 : RUN docker-php-ext-install mcrypt zip bcmath intl mbstring mysqli pdo_mysql exif xmlrpc     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd
 ---> Using cache
 ---> 13012bdb97e6
Step 4/11 : RUN pecl install -o -f oauth mongodb amqp-1.8.0     && rm -rf /tmp/pear
 ---> Running in d197ab9be520
No releases available for package "pecl.php.net/oauth"
No releases available for package "pecl.php.net/mongodb"
No releases available for package "pecl.php.net/amqp"
install failed
ERROR: Service 'php' failed to build: The command '/bin/sh -c pecl install -o -f oauth mongodb amqp-1.8.0     && rm -rf /tmp/pear' returned a non-zero code: 1

找不到这些PHP扩展

***pecl.php.net/oauth***
***pecl.php.net/mongodb***
***pecl.php.net/amqp***

> RUN pecl install -o -f oauth mongodb amqp-1.8.0 \
    && rm -rf /tmp/pear

**Comment by fancyecommerce** [comment]
有问题，直接官网论坛发帖子：http://www.fecmall.com/topic
