### ISSUE TITLE
build error -Package fxp/composer-asset-plugin at version ^1.4.4 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

### ISSUE THREAD

**Issue by marcelowu** [fecshop/yii2_fecshop_docker#29]
![Captura de tela de 2020-12-08 11-45-17](https://user-images.githubusercontent.com/30912144/101499011-83b5eb00-394b-11eb-8173-c2b6a864d456.png)

**Comment by onlyshow** [comment]
一样的问题，怎么解决的？
