### ISSUE TITLE
compose安装出现问题请教! 

### ISSUE THREAD

**Issue by superlyons** [fecshop/yii2_fecshop_docker#3]
你好! 我的环境是在vbox下运行centos7, docker版本为17.12.0-ce, compose版本为1.19, 我再执行sudo docker-compose build时遇到如下错误, 有劳如何解决? 谢谢!

xunsearch uses an image, skipping
mongodb uses an image, skipping
redis uses an image, skipping
mysql uses an image, skipping
Building php
Step 1/12 : FROM php:7.1.13-fpm
 ---> 3ac64cb99e11
Step 2/12 : RUN apt-get update && apt-get install -y         libfreetype6-dev         librabbitmq-dev         libssh-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libicu-dev         libxml2-dev         libssl-dev         git         wget         ssh         libpcre3-dev         --no-install-recommends
 ---> [Warning] IPv4 forwarding is disabled. Networking will not work.
 ---> Running in 850137f46d82
Err http://security.debian.org jessie/updates InRelease
  
Err http://deb.debian.org jessie InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Temporary failure resolving 'security.debian.org'
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Temporary failure resolving 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Temporary failure resolving 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Temporary failure resolving 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package libpcre3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libfreetype6-dev
E: Unable to locate package librabbitmq-dev
E: Unable to locate package libssh-dev
E: Unable to locate package libjpeg62-turbo-dev
E: Unable to locate package libmcrypt-dev
E: Unable to locate package libpng12-dev
E: Unable to locate package libicu-dev
E: Unable to locate package libxml2-dev
E: Unable to locate package libssl-dev
E: Unable to locate package git
E: Unable to locate package wget
E: Unable to locate package ssh
E: Package 'libpcre3-dev' has no installation candidate
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y         libfreetype6-dev         librabbitmq-dev         libssh-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libicu-dev         libxml2-dev         libssl-dev         git         wget         ssh         libpcre3-dev         --no-install-recommends' returned a non-zero code: 100

**Comment by superlyons** [comment]
解决办法：
# vi /etc/sysctl.conf
或者
# vi /usr/lib/sysctl.d/00-system.conf
添加如下代码：
    net.ipv4.ip_forward=1

重启network服务
# systemctl restart network

已找到!

**Comment by fancyecommerce** [comment]
好的，有问题，可以去www.fecshop.com发帖，当然这里也可以。

**Comment by thefreelight** [comment]
没解决呀，按照这个方法
