### ISSUE TITLE
构建出现错误

### ISSUE THREAD

**Issue by ruanyihang** [fecshop/yii2_fecshop_docker#8]
sudo docker-compose build 构建出现错误

Step 4/12 : RUN pecl install -o -f oauth mongodb amqp     && rm -rf /tmp/pear
 ---> Running in fc692c05f54c
No releases available for package "pecl.php.net/oauth"
No releases available for package "pecl.php.net/mongodb"
No releases available for package "pecl.php.net/amqp"
install failed
ERROR: Service 'php' failed to build: The command '/bin/sh -c pecl install -o -f oauth mongodb amqp     && rm -rf /tmp/pear' returned a non-zero code: 1
第4条后无法下载出现错误 
换成阿里云的那个会出现全部跳过的问题
xunsearch uses an image, skipping
mongodb uses an image, skipping
redis uses an image, skipping
mysql uses an image, skipping
php uses an image, skipping
web uses an image, skipping

**Comment by fancyecommerce** [comment]
1.你的问题应该是网络问题

2.使用阿里云构建，会比较快，如果你想完全重新构建可以使用命令：

`docker-compose build --no-cache`

3.如果想得到及时回复，请去www.fecshop.com发帖， http://www.fecshop.com/topic/624
